[RTC-216/217] Allow token to be set in config and update docs
jellyfish-dev/server_sdk_elixir pull request #5
Opened 2023-04-12 15:48 UTC by LVala

This PR contains [RTC-126](https://membraneframework.atlassian.net/jira/software/c/projects/RTC/boards/18?modal=detail&selectedIssue=RTC-216) and [RTC-217](https://membraneframework.atlassian.net/jira/software/c/projects/RTC/boards/18?modal=detail&selectedIssue=RTC-217) as they are closely related.

2023-04-12 16:33 UTC, mickel8 approved these changes

2023-04-12 16:33 UTC, mickel8 commented on lib/jellyfish/client.ex
> +  def new(address, token \\ nil)
That's a nitpick but I think I would go for `new/1` and `new/2`

2023-04-12 20:12 UTC, LVala commented on lib/jellyfish/client.ex
> +  def new(address, token \\ nil)
I'll do that, it seems like an obvious choice, I don't know why I went for the default argument.

2023-04-13 09:07 UTC, mickel8 requested changes

2023-04-13 09:07 UTC, mickel8 commented on README.md
> +{:ok, %Jellyfish.Peer{id: peer_id}, client_token} = Jellyfish.Room.add_peer(client, room_id, "webrtc")
```suggestion
{:ok, %Jellyfish.Peer{id: peer_id}, peer_token} = Jellyfish.Room.add_peer(client, room_id, "webrtc")
```

2023-04-13 09:07 UTC, mickel8 commented on lib/jellyfish/client.ex
> +  Creates new instance of `t:Jellyfish.Client.t/0`.
JFYI, you can also write `t:t/0` but the result will be slighlity different

2023-04-13 09:07 UTC, mickel8 commented on lib/jellyfish/room.ex
> +  @type client_token :: String.t()
Could we name this peer_token?

2023-04-13 09:33 UTC, mickel8 approved these changes

2023-04-13 09:34 UTC, merged